//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazy
    {
        public int id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.TimeSpan> TimeCreate { get; set; }
        public string CodClient { get; set; }
        public string Servic { get; set; }
        public string Stat { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public string TimeProcat { get; set; }
    }
}
